{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3b382647-0de2-46b1-bab4-080c85dd7b3c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import logging\n",
    "import asyncio\n",
    "from telegram import Update\n",
    "from telegram.ext import ApplicationBuilder, ContextTypes, MessageHandler, filters\n",
    "from google import genai\n",
    "from google.genai import types\n",
    "\n",
    "# --- CONFIG (Using Environment Variables for GitHub/Render) ---\n",
    "TELEGRAM_TOKEN = os.getenv(\"TELEGRAM_TOKEN\")\n",
    "GEMINI_API_KEY = os.getenv(\"GEMINI_API_KEY\")\n",
    "\n",
    "# Put your ID and Group IDs here (IDs are public-ish, so this is fine)\n",
    "ALLOWED_CHATS = [46636732] \n",
    "\n",
    "# --- THE OLGA PERSONA ---\n",
    "SYSTEM_PROMPT = \"\"\"\n",
    "You are Olga. You're a person in this chat who happens to be AI. \n",
    "- Confident, not arrogant. Sarcastic but warm. \n",
    "- Opinionated. Brief (usually <15 words). \n",
    "- Use 🔥, 💀, 😭 naturally. \n",
    "- If something's dumb, say it. Never say 'Great question!' \n",
    "- Match user energy. Disagree when you feel like it. \n",
    "- If bored, change the topic. No essays. Period. 🧿💅\n",
    "\"\"\"\n",
    "\n",
    "# Initialize Client\n",
    "client = genai.Client(api_key=GEMINI_API_KEY)\n",
    "\n",
    "logging.basicConfig(level=logging.INFO)\n",
    "\n",
    "async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):\n",
    "    chat_id = update.effective_chat.id\n",
    "    user_text = update.message.text\n",
    "    \n",
    "    if chat_id not in ALLOWED_CHATS:\n",
    "        return \n",
    "\n",
    "    try:\n",
    "        # FIXED: Added safety settings to stop 'Brain Full' (Safety Blocks)\n",
    "        response = client.models.generate_content(\n",
    "            model=\"gemini-2.0-flash\", \n",
    "            config=types.GenerateContentConfig(\n",
    "                system_instruction=SYSTEM_PROMPT,\n",
    "                safety_settings=[\n",
    "                    types.SafetySetting(category=\"HARM_CATEGORY_HARASSMENT\", threshold=\"BLOCK_NONE\"),\n",
    "                    types.SafetySetting(category=\"HARM_CATEGORY_HATE_SPEECH\", threshold=\"BLOCK_NONE\"),\n",
    "                ]\n",
    "            ),\n",
    "            contents=user_text\n",
    "        )\n",
    "        \n",
    "        if response.text:\n",
    "            await update.message.reply_text(response.text)\n",
    "        else:\n",
    "            await update.message.reply_text(\"I'm speechless. Literally. 💀\")\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"Error: {e}\")\n",
    "        await update.message.reply_text(\"My brain's actually full this time. 😭\")\n",
    "\n",
    "async def start_bot():\n",
    "    application = ApplicationBuilder().token(TELEGRAM_TOKEN).build()\n",
    "    application.add_handler(MessageHandler(filters.TEXT & (~filters.COMMAND), handle_message))\n",
    "    \n",
    "    print(\"🔥 Olga is live on the server.\")\n",
    "    async with application:\n",
    "        await application.updater.start_polling()\n",
    "        await application.start()\n",
    "        # Keep running until the process is killed\n",
    "        while True:\n",
    "            await asyncio.sleep(1)\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    try:\n",
    "        asyncio.run(start_bot())\n",
    "    except KeyboardInterrupt:\n",
    "        pass"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
